// <auto-generated />
using System;
using System.Collections.Generic;
using ElGuerre.Tendero.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElGuerre.Tendero.Persistence.Migrations;

[DbContext(typeof(TenderoDbContext))]
[Migration("20260903080235_AddReturns")]
partial class _20260903080235_AddReturns
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ElGuerre.Tendero.Catalog.Domain.Product", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Brand")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("brand");

                b.Property<string>("Category")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("category");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Description")
                    .HasColumnType("jsonb")
                    .HasColumnName("description");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("name");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("slug");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<string>("_attributes")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("jsonb")
                    .HasColumnName("attributes")
                    .HasDefaultValueSql("'[]'::jsonb");

                b.Property<string>("_variantAxes")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("jsonb")
                    .HasColumnName("variant_axes")
                    .HasDefaultValueSql("'[]'::jsonb");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ElGuerre.Tendero.Catalog.Domain.Product.Price#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasPrecision(18, 2)
                            .HasColumnType("numeric(18,2)")
                            .HasColumnName("price_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasMaxLength(3)
                            .HasColumnType("character varying(3)")
                            .HasColumnName("price_currency");
                    });

                b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_images", "ElGuerre.Tendero.Catalog.Domain.Product._images#ProductImage", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("Alt")
                            .HasJsonPropertyName("alt");

                        b1.Property<string>("Id")
                            .IsRequired()
                            .HasJsonPropertyName("id");

                        b1.Property<int>("SortOrder")
                            .HasJsonPropertyName("sortOrder");

                        b1
                            .ToJson("images")
                            .HasColumnType("jsonb");
                    });

                b.HasKey("Id")
                    .HasName("pk_products");

                b.ToTable("products", "catalog");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Catalog.Domain.Variant", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Image")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("image_id");

                b.Property<Guid?>("ProductId")
                    .HasColumnType("uuid")
                    .HasColumnName("product_id");

                b.Property<string>("Sku")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("sku");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<string>("TaxClass")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("tax_class");

                b.Property<string>("_axisValues")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("axis_values");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ElGuerre.Tendero.Catalog.Domain.Variant.Price#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasPrecision(18, 2)
                            .HasColumnType("numeric(18,2)")
                            .HasColumnName("price_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasMaxLength(3)
                            .HasColumnType("character varying(3)")
                            .HasColumnName("price_currency");
                    });

                b.HasKey("Id")
                    .HasName("pk_variants");

                b.HasIndex("ProductId")
                    .HasDatabaseName("ix_variants_product_id");

                b.HasIndex("Sku")
                    .IsUnique()
                    .HasDatabaseName("ix_variants_sku");

                b.ToTable("variants", "catalog");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Inventory.Domain.Reservation", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("order_id");

                b.Property<string>("Reason")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("reason");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_lines", "ElGuerre.Tendero.Inventory.Domain.Reservation._lines#ReservationLine", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<int>("Quantity")
                            .HasJsonPropertyName("quantity");

                        b1.Property<string>("Sku")
                            .IsRequired()
                            .HasJsonPropertyName("sku");

                        b1.Property<string>("WarehouseCode")
                            .IsRequired()
                            .HasJsonPropertyName("warehouseCode");

                        b1
                            .ToJson("lines")
                            .HasColumnType("jsonb");
                    });

                b.HasKey("Id")
                    .HasName("pk_reservations");

                b.HasIndex("OrderId")
                    .IsUnique()
                    .HasDatabaseName("ix_reservations_order_id");

                b.ToTable("reservations", "inventory");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Inventory.Domain.StockItem", b =>
            {
                b.Property<string>("Sku")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("sku");

                b.Property<string>("WarehouseCode")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("warehouse_code");

                b.Property<int>("OnHand")
                    .HasColumnType("integer")
                    .HasColumnName("on_hand");

                b.Property<int>("Reserved")
                    .HasColumnType("integer")
                    .HasColumnName("reserved");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("Sku", "WarehouseCode")
                    .HasName("pk_stock_items");

                b.HasIndex("Sku")
                    .HasDatabaseName("ix_stock_items_sku");

                b.ToTable("stock_items", "inventory");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Ordering.Domain.Cart", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Culture")
                    .IsRequired()
                    .HasMaxLength(5)
                    .HasColumnType("character varying(5)")
                    .HasColumnName("culture");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("currency");

                b.Property<Guid?>("CustomerId")
                    .HasColumnType("uuid")
                    .HasColumnName("customer_id");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("token");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_lines", "ElGuerre.Tendero.Ordering.Domain.Cart._lines#CartLine", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("ImageId")
                            .HasJsonPropertyName("imageId");

                        b1.Property<Guid>("ProductId")
                            .HasJsonPropertyName("productId");

                        b1.Property<string>("ProductName")
                            .IsRequired()
                            .HasJsonPropertyName("productName");

                        b1.Property<int>("Quantity")
                            .HasJsonPropertyName("quantity");

                        b1.Property<string>("Sku")
                            .IsRequired()
                            .HasJsonPropertyName("sku");

                        b1.Property<Guid>("VariantId")
                            .HasJsonPropertyName("variantId");

                        b1.Property<string>("VariantLabel")
                            .HasJsonPropertyName("variantLabel");

                        b1
                            .ToJson("lines")
                            .HasColumnType("jsonb");
                    });

                b.HasKey("Id")
                    .HasName("pk_carts");

                b.HasIndex("Token")
                    .IsUnique()
                    .HasDatabaseName("ix_carts_token");

                b.HasIndex("Status", "ExpiresAt")
                    .HasDatabaseName("ix_carts_status_expires_at");

                b.ToTable("carts", "ordering");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Ordering.Domain.Order", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("Culture")
                    .IsRequired()
                    .HasMaxLength(5)
                    .HasColumnType("character varying(5)")
                    .HasColumnName("culture");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("character varying(3)")
                    .HasColumnName("currency");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uuid")
                    .HasColumnName("customer_id");

                b.Property<string>("IdempotencyKey")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("idempotency_key");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.ComplexProperty(typeof(Dictionary<string, object>), "BillingAddress", "ElGuerre.Tendero.Ordering.Domain.Order.BillingAddress#Address", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("City")
                            .IsRequired()
                            .HasJsonPropertyName("city");

                        b1.Property<string>("CountryCode")
                            .IsRequired()
                            .HasJsonPropertyName("countryCode");

                        b1.Property<string>("Line1")
                            .IsRequired()
                            .HasJsonPropertyName("line1");

                        b1.Property<string>("Line2")
                            .HasJsonPropertyName("line2");

                        b1.Property<string>("Phone")
                            .HasJsonPropertyName("phone");

                        b1.Property<string>("PostalCode")
                            .IsRequired()
                            .HasJsonPropertyName("postalCode");

                        b1.Property<string>("RecipientName")
                            .IsRequired()
                            .HasJsonPropertyName("recipientName");

                        b1.Property<string>("Region")
                            .HasJsonPropertyName("region");

                        b1
                            .ToJson("billing_address")
                            .HasColumnType("jsonb");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Payment", "ElGuerre.Tendero.Ordering.Domain.Order.Payment#OrderPayment", b1 =>
                    {
                        b1.Property<string>("AuthorizationId")
                            .IsRequired()
                            .HasJsonPropertyName("authorizationId");

                        b1.Property<string>("CaptureId")
                            .HasJsonPropertyName("captureId");

                        b1.Property<string>("Provider")
                            .IsRequired()
                            .HasJsonPropertyName("provider");

                        b1
                            .ToJson("payment")
                            .HasColumnType("jsonb");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Quote", "ElGuerre.Tendero.Ordering.Domain.Order.Quote#OrderQuote", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("InputHash")
                            .IsRequired()
                            .HasJsonPropertyName("inputHash");

                        b1.Property<DateTimeOffset>("IssuedAt")
                            .HasJsonPropertyName("issuedAt");

                        b1.Property<string>("QuoteId")
                            .IsRequired()
                            .HasJsonPropertyName("quoteId");

                        b1
                            .ToJson("quote")
                            .HasColumnType("jsonb");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Shipping", "ElGuerre.Tendero.Ordering.Domain.Order.Shipping#OrderShipping", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("Amount")
                            .IsRequired()
                            .HasJsonPropertyName("amount");

                        b1.Property<int?>("EstimatedDays")
                            .HasJsonPropertyName("estimatedDays");

                        b1.Property<string>("Label")
                            .IsRequired()
                            .HasJsonPropertyName("label");

                        b1.Property<string>("OptionCode")
                            .IsRequired()
                            .HasJsonPropertyName("optionCode");

                        b1
                            .ToJson("shipping")
                            .HasColumnType("jsonb");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "ElGuerre.Tendero.Ordering.Domain.Order.ShippingAddress#Address", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("City")
                            .IsRequired()
                            .HasJsonPropertyName("city");

                        b1.Property<string>("CountryCode")
                            .IsRequired()
                            .HasJsonPropertyName("countryCode");

                        b1.Property<string>("Line1")
                            .IsRequired()
                            .HasJsonPropertyName("line1");

                        b1.Property<string>("Line2")
                            .HasJsonPropertyName("line2");

                        b1.Property<string>("Phone")
                            .HasJsonPropertyName("phone");

                        b1.Property<string>("PostalCode")
                            .IsRequired()
                            .HasJsonPropertyName("postalCode");

                        b1.Property<string>("RecipientName")
                            .IsRequired()
                            .HasJsonPropertyName("recipientName");

                        b1.Property<string>("Region")
                            .HasJsonPropertyName("region");

                        b1
                            .ToJson("shipping_address")
                            .HasColumnType("jsonb");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Totals", "ElGuerre.Tendero.Ordering.Domain.Order.Totals#OrderTotals", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("DiscountTotal")
                            .IsRequired()
                            .HasJsonPropertyName("discountTotal");

                        b1.Property<string>("Shipping")
                            .IsRequired()
                            .HasJsonPropertyName("shipping");

                        b1.Property<string>("Subtotal")
                            .IsRequired()
                            .HasJsonPropertyName("subtotal");

                        b1.Property<string>("TaxTotal")
                            .IsRequired()
                            .HasJsonPropertyName("taxTotal");

                        b1.Property<string>("Total")
                            .IsRequired()
                            .HasJsonPropertyName("total");

                        b1
                            .ToJson("totals")
                            .HasColumnType("jsonb");
                    });

                b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_discounts", "ElGuerre.Tendero.Ordering.Domain.Order._discounts#OrderDiscount", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("Amount")
                            .IsRequired()
                            .HasJsonPropertyName("amount");

                        b1.Property<string>("Label")
                            .IsRequired()
                            .HasJsonPropertyName("label");

                        b1.Property<string>("PromotionCode")
                            .IsRequired()
                            .HasJsonPropertyName("promotionCode");

                        b1
                            .ToJson("discounts")
                            .HasColumnType("jsonb");
                    });

                b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_lines", "ElGuerre.Tendero.Ordering.Domain.Order._lines#OrderLine", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<Guid>("ProductId")
                            .HasJsonPropertyName("productId");

                        b1.Property<string>("ProductName")
                            .IsRequired()
                            .HasJsonPropertyName("productName");

                        b1.Property<int>("Quantity")
                            .HasJsonPropertyName("quantity");

                        b1.Property<string>("Sku")
                            .IsRequired()
                            .HasJsonPropertyName("sku");

                        b1.Property<string>("UnitPrice")
                            .IsRequired()
                            .HasJsonPropertyName("unitPrice");

                        b1.Property<Guid>("VariantId")
                            .HasJsonPropertyName("variantId");

                        b1.Property<string>("VariantLabel")
                            .HasJsonPropertyName("variantLabel");

                        b1
                            .ToJson("lines")
                            .HasColumnType("jsonb");
                    });

                b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_taxes", "ElGuerre.Tendero.Ordering.Domain.Order._taxes#OrderTax", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("Amount")
                            .IsRequired()
                            .HasJsonPropertyName("amount");

                        b1.Property<string>("Base")
                            .IsRequired()
                            .HasJsonPropertyName("base");

                        b1.Property<decimal>("Rate")
                            .HasJsonPropertyName("rate");

                        b1.Property<string>("TaxClass")
                            .IsRequired()
                            .HasJsonPropertyName("taxClass");

                        b1
                            .ToJson("taxes")
                            .HasColumnType("jsonb");
                    });

                b.HasKey("Id")
                    .HasName("pk_orders");

                b.HasIndex("IdempotencyKey")
                    .IsUnique()
                    .HasDatabaseName("ix_orders_idempotency_key");

                b.ToTable("orders", "ordering");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Ordering.Domain.ReturnRequest", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<Guid>("CustomerId")
                    .HasColumnType("uuid")
                    .HasColumnName("customer_id");

                b.Property<Guid>("OrderId")
                    .HasColumnType("uuid")
                    .HasColumnName("order_id");

                b.Property<string>("RefundAmount")
                    .HasColumnType("text")
                    .HasColumnName("refund_amount");

                b.Property<string>("RefundReference")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("refund_reference");

                b.Property<string>("Resolution")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("resolution");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.ComplexCollection(typeof(List<Dictionary<string, object>>), "_lines", "ElGuerre.Tendero.Ordering.Domain.ReturnRequest._lines#ReturnLine", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<string>("Comment")
                            .HasJsonPropertyName("comment");

                        b1.Property<int>("Quantity")
                            .HasJsonPropertyName("quantity");

                        b1.Property<string>("Reason")
                            .IsRequired()
                            .HasJsonPropertyName("reason");

                        b1.Property<string>("Sku")
                            .IsRequired()
                            .HasJsonPropertyName("sku");

                        b1.Property<Guid>("VariantId")
                            .HasJsonPropertyName("variantId");

                        b1
                            .ToJson("lines")
                            .HasColumnType("jsonb");
                    });

                b.HasKey("Id")
                    .HasName("pk_return_requests");

                b.HasIndex("OrderId")
                    .HasDatabaseName("ix_return_requests_order_id");

                b.HasIndex("Status")
                    .HasDatabaseName("ix_return_requests_status");

                b.ToTable("return_requests", "ordering");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Persistence.Outbox.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("Attempts")
                    .HasColumnType("integer")
                    .HasColumnName("attempts");

                b.Property<string>("Error")
                    .HasMaxLength(4000)
                    .HasColumnType("character varying(4000)")
                    .HasColumnName("error");

                b.Property<DateTimeOffset>("OccurredAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("occurred_at");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("payload");

                b.Property<DateTimeOffset?>("ProcessedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("processed_at");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("type");

                b.HasKey("Id")
                    .HasName("pk_messages");

                b.HasIndex("ProcessedAt", "OccurredAt")
                    .HasDatabaseName("ix_messages_processed_at_occurred_at")
                    .HasFilter("processed_at IS NULL");

                b.ToTable("messages", "outbox");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Catalog.Domain.Product", b =>
            {
                b.OwnsMany("ElGuerre.Tendero.Catalog.Domain.ExternalReference", "ExternalReferences", b1 =>
                    {
                        b1.Property<Guid>("ProductId")
                            .HasColumnType("uuid")
                            .HasColumnName("product_id");

                        b1.Property<string>("Source")
                            .HasMaxLength(50)
                            .HasColumnType("character varying(50)")
                            .HasColumnName("source");

                        b1.Property<string>("ExternalId")
                            .HasMaxLength(400)
                            .HasColumnType("character varying(400)")
                            .HasColumnName("external_id");

                        b1.HasKey("ProductId", "Source", "ExternalId")
                            .HasName("pk_product_external_references");

                        b1.HasIndex("Source", "ExternalId")
                            .IsUnique()
                            .HasDatabaseName("ix_product_external_references_source_external_id");

                        b1.ToTable("product_external_references", "catalog");

                        b1.WithOwner()
                            .HasForeignKey("ProductId")
                            .HasConstraintName("fk_product_external_references_products_product_id");
                    });

                b.Navigation("ExternalReferences");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Catalog.Domain.Variant", b =>
            {
                b.HasOne("ElGuerre.Tendero.Catalog.Domain.Product", null)
                    .WithMany("Variants")
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("fk_variants_products_product_id");
            });

        modelBuilder.Entity("ElGuerre.Tendero.Catalog.Domain.Product", b =>
            {
                b.Navigation("Variants");
            });
#pragma warning restore 612, 618
    }
}
